### PR TITLE
Added reading direction

### PR DESCRIPTION
**Pull request by defanor**
References #13.

### CODE REVIEW

**Comment by ocharles** [comment]
This looks good to me. Have you confirmed it's behaving as you want?

**Comment by defanor** [comment]
Actually, haven't checked enough: it appears to skip the most recent
record when reading backwards from the end. Will fix now.

**Comment by defanor** [comment]
It would also stuck after reaching the beginning, fixed that
too. Appears to work fine now.

I'm planning to use it (and hence test more) this week, so if we want
to be extra safe, this PR may wait a few days.

**Comment by ocharles** [comment]
Sounds good - if you could ping me once you're happy with it we'll get this to Hackage. Thanks!

**Comment by defanor** [comment]
Sure.

Refined the new code a little with the last push.

**Comment by defanor** [comment]
Implemented what I needed it for, everything works as expected. So,
I'm happy with it.

**Comment by ocharles** [comment]
Fantastic, thank you!

**Pull request merged**
